pipelines:
  CSharp-Lib:
    group: Gauge-Csharp
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-csharp-lib.git
    stages:
      - test:
          jobs:
            test:
              resources:
               - windows
               - package
              tasks:
               - exec:
                   command: build
                   arguments:
                    - build
               - exec:
                   command: build
                   arguments:
                    - test
      - package:
          jobs:
            package:
              resources:
               - windows
               - package
              tasks:
               - exec:
                   command: build
                   arguments:
                    - build
               - exec:
                   command: build
                   arguments:
                    - package
              artifacts:
               - build:
                   source: artifacts/
      - release:
          approval: manual
          jobs:
            nuget:
              tasks:
                - fetch:
                  pipeline: CSharp-Lib
                  stage: package
                  job: package
                  source: artifacts
                - exec:
                  command: powershell.exe
                  working_directory: artifacts
                  arguments:
                    - -command
                    - "try{gci Gauge.CSharp.Lib*.nupkg | select -f 1 | %{nuget.exe push $_ $env:NUGET_API_KEY -Source https://www.nuget.org/api/v2/package}}catch{Write-Error $_;exit -1}"
