environments:
  all:
    pipelines:
      - dotnet-build
      - dotnet-package
      - dotnet-FT
pipelines:
  dotnet-build:
    group: Gauge-Dotnet
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-dotnet.git
    stages:
      - build:
          jobs:
            unit-test:
              resources:
               - windows
              tasks:
               - exec:
                   command: run
                   arguments:
                    - test
  dotnet-package:
    group: Gauge-Dotnet
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-dotnet.git
      upstream:
        pipeline: dotnet-build
        stage: build
    stages:
      - artifact:
          jobs:
            installer:
              resources:
               - windows
              tasks:
               - exec:
                   command: run
                   arguments:
                    - package
              artifacts:
               - build:
                   source: artifacts/
  dotnet-FT:
    group: Gauge-Dotnet
    materials:
      gauge-tests:
        git: https://github.com/getgauge/gauge-tests.git
      package:
        pipeline: dotnet-package
        stage: artifact
      gauge:
        pipeline: Gauge-Package
        stage: sign
    stages:
      - build:
          jobs:
            FT:
              resources:
               - windows
               - FT
              environment_variables:
                GAUGE_ROOT: C:/gauge_root
                JAVA_HOME: C:\Program Files\Java\jdk1.8.0_121
              tasks:
               - fetch:
                   pipeline: Gauge-Package
                   stage: sign
                   job: windows
                   is_file: yes
                   source: test_installers/gauge-windows.x86_64.exe
               - fetch:
                   pipeline: dotnet-package
                   stage: artifact
                   job: installer
                   source: artifacts
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "gauge-windows.x86_64.exe /S /D=%GAUGE_ROOT%"
               - exec:
                   command: cmd
                   arguments:
                    - /c
                    - "%GAUGE_ROOT%/bin/gauge"
                    - uninstall
                    - dotnet
               - exec:
                   working_directory: artifacts
                   command: cmd
                   arguments:
                    - /c
                    - "for %f in (gauge-dotnet*.zip) do %GAUGE_ROOT%/bin/gauge install dotnet -f %f"
               - exec:
                   command: gauge
                   arguments:
                    - install
               - exec:
                   command: mvn
                   arguments:
                    - -q
                    - clean
                    - install
                    - -Denv=ci-dotnet
                    - -Dnodes=4
                    - -Dtags="csharp"
                    - -DinParallel=true
  dotnet-release:
    group: Gauge-Dotnet
    materials:
      package:
        pipeline: dotnet-package
        stage: artifact
      dotnet-FT:
        pipeline: dotnet-FT
        stage: build
    stages:
      - release:
          approval: manual
          jobs:
            github:
              elastic_profile_id: gauge-centos-all
              environment_variables:
                repoName: gauge-dotnet
              secure_variables:
                GITHUB_TOKEN: "NQJXCgXvHwzebDC27DfhkpsmjcMjRNwbguFJXdMvVXJyw5eSaKXE2EFPgji/6/ug"
              tasks:
               - fetch:
                   pipeline: dotnet-package
                   stage: artifact
                   job: installer
                   source: artifacts/gauge-dotnet*.zip
                   is_file: yes
               - exec:
                   command: /bin/sh
                   arguments:
                    - -c
                    - (curl -sSfL https://github.com/getgauge/gauge/raw/master/build/github_release.sh | sh)